#!/usr/bin/env node
/* Regenerates sitemap.xml from js/data.js and js/listing-rules.js — Phase 3's
 * static equivalent of GET /sitemap.xml (FR-SEO-003: "generated from
 * currently published Locations, Experiences and Properties").
 *
 * Run with: node scripts/generate-sitemap.js
 *
 * Deliberately does NOT include a <url> entry per filtered listing-page view
 * (e.g. tourism.html?location=darjeeling) — the site's own canonical-URL
 * convention (FR-URL-005) says a filtered view's canonical tag should point
 * at the unfiltered page, specifically to avoid exactly the duplicate-content
 * indexing this script would otherwise cause. Locations and Experiences
 * likewise have no separate detail page to list (see js/taxonomy.js's
 * documented decision not to build one), so they aren't enumerated here
 * either — only real, distinct pages are, plus one <url> per published
 * property via its distinct ?slug= URL, which previously wasn't in the
 * sitemap at all.
 */

'use strict';

var fs = require('fs');
var path = require('path');

require(path.join(__dirname, '..', 'js', 'taxonomy.js'));
require(path.join(__dirname, '..', 'js', 'listing-rules.js'));
require(path.join(__dirname, '..', 'js', 'data.js'));

var data = global.AvanyaData;
var listingRules = global.AvanyaListingRules;

var BASE_URL = 'https://www.avanyatourism.example';

var staticPages = [
  { loc: '/index.html', changefreq: 'weekly', priority: '1.0' },
  { loc: '/tourism.html', changefreq: 'weekly', priority: '0.9' },
  { loc: '/real-estate.html', changefreq: 'weekly', priority: '0.9' },
  { loc: '/travel-plan.html', changefreq: 'monthly', priority: '0.6' },
  { loc: '/search.html', changefreq: 'monthly', priority: '0.4' },
  { loc: '/about.html', changefreq: 'monthly', priority: '0.6' },
  { loc: '/contact.html', changefreq: 'monthly', priority: '0.7' }
];

var propertyEntries = listingRules.getPublishedListings(data.ALL_LISTINGS).map(function (item) {
  return {
    loc: '/property.html?slug=' + encodeURIComponent(item.slug),
    changefreq: 'weekly',
    priority: item.module === 'tourism' ? '0.8' : '0.7'
  };
});

var allEntries = staticPages.concat(propertyEntries);

var xml = '<?xml version="1.0" encoding="UTF-8"?>\n' +
  '<!--\n' +
  '  Generated by scripts/generate-sitemap.js — do not hand-edit. Re-run that\n' +
  '  script after adding, removing, or unpublishing a listing in js/data.js.\n' +
  '  Each published Tourism/Real Estate listing gets its own <url> entry via\n' +
  '  its distinct ?slug= URL; filtered listing-page views and taxonomy\n' +
  '  (Location/Experience) entries are deliberately excluded — see the header\n' +
  '  comment in this script for why.\n' +
  '-->\n' +
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
  allEntries.map(function (e) {
    return '  <url>\n' +
      '    <loc>' + BASE_URL + e.loc + '</loc>\n' +
      '    <changefreq>' + e.changefreq + '</changefreq>\n' +
      '    <priority>' + e.priority + '</priority>\n' +
      '  </url>';
  }).join('\n') + '\n' +
  '</urlset>\n';

var outPath = path.join(__dirname, '..', 'sitemap.xml');
fs.writeFileSync(outPath, xml, 'utf8');
console.log('Wrote ' + outPath + ' with ' + allEntries.length + ' URLs (' + staticPages.length + ' static pages + ' + propertyEntries.length + ' published listings).');
